// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0O_XcZhJzEO2ZCIgUgp98XA4cXA-srVs',
    appId: '1:544962029679:web:ce72603757a059f9a5859a',
    messagingSenderId: '544962029679',
    projectId: 'teentalktalk-8e9d6',
    authDomain: 'teentalktalk-8e9d6.firebaseapp.com',
    storageBucket: 'teentalktalk-8e9d6.appspot.com',
    measurementId: 'G-7G28E9ZG1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5SWgREcTi045cVjocNdH5XCWYjSd0sec',
    appId: '1:544962029679:android:8aec91bf5f5ee6f9a5859a',
    messagingSenderId: '544962029679',
    projectId: 'teentalktalk-8e9d6',
    storageBucket: 'teentalktalk-8e9d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn7bftZkjpxv3AfQbguQ8Y2IzQM-GXZyY',
    appId: '1:544962029679:ios:812165e55678e4b5a5859a',
    messagingSenderId: '544962029679',
    projectId: 'teentalktalk-8e9d6',
    storageBucket: 'teentalktalk-8e9d6.appspot.com',
    iosClientId:
        '544962029679-0ujfndnmfsuj9r8ks6ukaq1gecvvcrc6.apps.googleusercontent.com',
    iosBundleId: 'com.naru.teenTalkTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn7bftZkjpxv3AfQbguQ8Y2IzQM-GXZyY',
    appId: '1:544962029679:ios:812165e55678e4b5a5859a',
    messagingSenderId: '544962029679',
    projectId: 'teentalktalk-8e9d6',
    storageBucket: 'teentalktalk-8e9d6.appspot.com',
    iosClientId:
        '544962029679-0ujfndnmfsuj9r8ks6ukaq1gecvvcrc6.apps.googleusercontent.com',
    iosBundleId: 'com.naru.teenTalkTalk',
  );
}
